### ISSUE TITLE
Produce single sketch from multiple input files

### ISSUE THREAD

**Issue by bede** [dnbaker/dashing#26]
I'd like to produce a single sketch from multiple input files – forward and reverse reads in this case. Is this possible with Dashing?

Mash lets me do it like this:
```
mash sketch -m 5 -I ec_r12 -o ec_r12_sketch ec_1.fq.gz ec_2.fq.gz
```

Else by piping to stdin:
```
cat ec_1.fq.gz ec_2.fq.gz | mash sketch -m 5 -I ec_r12 -o ec_r12_sketch -
```

**Comment by dnbaker** [comment]
Currently, this is only supported with the union subcommand, but we are working to support multiple files per sketch out of the box. (One would need to ‘dashing sketch’ both fastqs and ‘dashing union in1.fq.hll in2.fq.hll -o in.hll’.)

Thanks for the request! I’ll prioritize this more, as it’s not the first time it’s been mentioned. I’m traveling currently, but hope to have time in the next week.

**Comment by bede** [comment]
Ah, I'd overlooked the union subcommand, thanks : )

**Comment by dnbaker** [comment]
Hi!

I know this took a while. However, I believe I have this supported in the [pairs](https://github.com/dnbaker/dashing/tree/pairs) branch which, after some large-scale testing, I expect to merge into master relatively soon.

To signify that multiple filenames are sources for one sketch, delimit an arbitrary number of filenames on the same line in the file from the `-F` flag.

**Comment by dnbaker** [comment]
Currently, this is supported by using the -F/-Q parameters to pass in files and listing multiple per file, separating them by a space. I'm closing for now, but feel free to open if you have any further issues.
