### ISSUE TITLE
Unable to install (error with make file)

### ISSUE THREAD

**Issue by seanaller** [dnbaker/dashing#30]
Hi there,

I'm having an issue when attempting to install dashing via
`make dashing`

I get the following error:

> make: *** No rule to make target `bonsai/hll/include/cbf.h', needed by `src/dashing.o'.  Stop.

Any suggestions?

**Comment by dnbaker** [comment]
It sounds like you didn't clone recursively; we use submodules as a way of providing dependencies. You can fix this by running `git submodule update --init --recursive` from the directory where you cloned it, or, alternatively, delete the dashing directory and `git clone --recursive https://github.com/dnbaker/dashing && cd dashing && make dashing`.

I've updated the README to reflect this better; in refactoring, I left the verbal instruction to clone recursively but didn't update the build commands.

Let me know if you have any further problems!

**Comment by seanaller** [comment]
> It sounds like you didn't clone recursively; we use submodules as a way of providing dependencies. You can fix this by running `git submodule update --init --recursive` from the directory where you cloned it, or, alternatively, delete the dashing directory and `git clone --recursive https://github.com/dnbaker/dashing && cd dashing && make dashing`.

That was exactly it! Thanks for that.
