### ISSUE TITLE
Can we bring dashing to bioconda?

### ISSUE THREAD

**Issue by SilasK** [dnbaker/dashing#31]

**Comment by dnbaker** [comment]
A previous version was, under the name `dash`, but it would be worth merging it in. I haven't integrated any bioconda packages before, so I'll need to learn how.

The other issue is the CPU backend -- whether it uses SSE4.1, AVX2, or AVX512. We currently release 3 statically linked binaries (one for each), but if we can count on gcc 5.4 or newer, it's probably doable. (And it would automatically select the best version.)

**Comment by SilasK** [comment]
Seems it doesn't work perfectly on macOS.

```
$ dashing mkdist --help
Dashing version: v0.4.0
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error
Abort trap: 6

```

**Comment by dnbaker** [comment]
mkdist needs some specific work, but that's not a primary use case. I'll give it a look when I'm done traveling -- are sketch/dist running?

**Comment by SilasK** [comment]
The help message is not completely clear.

But yes distilled works.

**Comment by dnbaker** [comment]
Apparently libc++ doesn't emit the runtime error message, while libstdc++ does. I'll modify the RUNTIME_ERROR macro to emit the `exception::what()` string. Thanks for letting me know. This will be addressed in the next release.

For example, running this under gcc emits:

```
Dashing version: v0.4.0-3-g9517
**terminate called after throwing an instance of 'std::runtime_error'
  what():  [src/mkdistmain.cpp:int bns::mkdist_main(int, char**)11] required: --multik <outpref>,<start>,<end> [optional: ,<step>]**
```

**Comment by dnbaker** [comment]
I'll close this for now unless there are any objections, but I'll take a look at updating the bioconda rule for version 0.4+ sometime in the next few weeks. Thanks!
