### ISSUE TITLE
example files

### ISSUE THREAD

**Issue by maojn** [dnbaker/dashing#36]
Hi,

Are there example files somewhere I can download to test dashing? Thanks.
Jean

**Comment by dnbaker** [comment]
Hi Jean,

You might actually already have some example files already in `dashing/bonsai/test/`, as `GCF*.gz` (such as GCF_000302455.1_ASM30245v1_genomic.fna.gz). (You will if you cloned recursively, though not if you installed through conda.)

If not, you can download them from [this folder](https://github.com/dnbaker/bonsai/tree/master/test) here, or, alternatively, acquire some genome assemblies from [RefSeq](ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/).  If you want to download them programmatively, our [download_genomes.py](https://github.com/dnbaker/bonsai/blob/master/python/download_genomes.py) script might be handy.

Let me know if you have any more questions.

**Comment by maojn** [comment]
Thank you for your prompt reply. In your README file it says:
dashing dist -k31 -p13 -Odistance_matrix.txt -osize_estimates.txt genome1.fna.gz genome2.fna genome3.fasta <...>

Is it possible for you to provide all the required input files and the exact command to use so that I can test run real quick? I am installing dashing for users in our community. Just want to make sure it works before I let users know. I don't work in the field and don't have required files handy. Thank you very much.

Regards,

**Comment by dnbaker** [comment]
Why don't you try running these lines from the Travis CI configuration?

https://github.com/dnbaker/dashing/blob/master/.travis.yml#L17-L18?

You can do this by:

```
git clone --recursive https://github.com/dnbaker/dashing/ && cd dashing && make dashing
./dashing dist bonsai/test/GCF_00*z
./dashing dist -8 bonsai/test/GCF_00*z
```
It should emit output similar to
```
Dashing version: v0.4.2-8-ga744
#Path	Size (est.)
bonsai/test/GCF_001723155.1_ASM172315v1_genomic.fna.gz	4829255
bonsai/test/GCF_000302455.1_ASM30245v1_genomic.fna.gz	2718859
bonsai/test/GCF_000953115.1_DSM1535_genomic.fna.gz	2433839
bonsai/test/GCF_000762265.1_ASM76226v1_genomic.fna.gz	2368528
##Names	bonsai/test/GCF_001723155.1_ASM172315v1_genomic.fna.gz	bonsai/test/GCF_000302455.1_ASM30245v1_genomic.fna.gz	bonsai/test/GCF_000953115.1_DSM1535_genomic.fna.gz	bonsai/test/GCF_000762265.1_ASM76226v1_genomic.fna.gz
bonsai/test/GCF_001723155.1_ASM172315v1_genomic.fna.gz	-	0	0	0
bonsai/test/GCF_000302455.1_ASM30245v1_genomic.fna.gz	-	-	0	0
bonsai/test/GCF_000953115.1_DSM1535_genomic.fna.gz	-	-	-	0.550403
bonsai/test/GCF_000762265.1_ASM76226v1_genomic.fna.gz	-	-	-	-
```

**Comment by maojn** [comment]
It worked! Thank you very much!

**Comment by dnbaker** [comment]
Great! Let me know if you have any further questions.
