### ISSUE TITLE
make clean does not propagate

### ISSUE THREAD

**Issue by karel-brinda** [dnbaker/dashing#5]
This is rather a minor issue. When I am experimenting with different compilation options, I need to clean all intermediate files. However, `make clean` works only on the top level and does not propagate. This can be done by adding lines like `$(MAKE) -C bonsai clean`. I would create a pull request, but I am not sure if `make clean` is done properly in bonsai and distmat. Also, `git clean` cannot work recursively so this wouldn't be a solution.

**Comment by dnbaker** [comment]
Good catch!

bonsai and distmat are actually used in header-only fashion, so we don't need to clean them, but zlib and zstd should be cleaned. I've made this correction in this commit: https://github.com/dnbaker/dashing/commit/c12dde31c4390feddd294377c04a8b25987346a4.

**Comment by dnbaker** [comment]
I appreciate the feedback, and please feel free to re-open the issue if you have any more/similar concerns, but until then I'll close this issue.
