### ISSUE TITLE
Build failure with AVX512

### ISSUE THREAD

**Issue by kloetzl** [dnbaker/dashing#6]
After cloning and updating the build fails at bonsai/hll/vec/vec.h:175 because `_mm512_mullo_si512` is [not a valid intrinsic](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#!=undefined&expand=2973,2998,686,685,684,682,3562,3630,516,767,771,765,3916,3916,3916,4754,4752,4754,771,4622,4679,4757,3611,4751,1033,3831,3833,909,1033,3831,294,4037,446,5160,5305,4935,5361,5302,5305,2907,3981&techs=MMX,SSE,SSE2,SSE3,SSSE3,SSE4_1,SSE4_2,AVX,AVX2,FMA,AVX_512,KNC,SVML,Other&text=_mm512_mullo_si512). This then leads to a huge number of follow up errors.

**Comment by dnbaker** [comment]
Thank you! I haven't been testing on AVX512 recently, and I must have introduced that bug. It should be `_mm512_mullo_epi64`. I'll correct this today (it shouldn't take long) and add tests for AVX512 to CI so that this doesn't happen again.

**Comment by dnbaker** [comment]
Sorry for the delay, the git issue took up a lot longer than I had expected. (But that's fixed, too!)

I've updated vec, bonsai, and dashing and built them on a Skylake cluster. Would you be willing to give it another shot?

**Comment by kloetzl** [comment]
With `v0.1.1-22-gd00454a` I get the following error:

```
In file included from bonsai/hll/hll.h:3,
                 from ./bonsai/bonsai/include/popcnt.h:8,
                 from ./bonsai/bonsai/include/util.h:35,
                 from src/dashing.cpp:4:
bonsai/hll/common.h: In function ‘sketch::common::VType sketch::common::multinv::f64(sketch::common::VType, sketch::common::VType)’:
bonsai/hll/common.h:327:22: error: ‘_mm_mullo_epi64’ is not a member of ‘vec’
         p1[i] = vec::_mm_mullo_epi64(p2[i], _mm_sub_epi64(_mm_set1_epi64x(2), vec::_mm_mullo_epi64(p1[i], p2[i])));
```

**Comment by dnbaker** [comment]
Thanks for the catch! This is an issue that wasn't picked up by the compilers I was using, as the multinv with VType wasn't being used, but it's now been corrected.

**Comment by kloetzl** [comment]
Now it builds; Thanks for the quick help!
