### ISSUE TITLE
Option to produce PHYLIP distance matrix format 

### ISSUE THREAD

**Issue by kloetzl** [dnbaker/dashing#8]
`dashing dist` produces a distance matrix in its own new file format that is incompatible with any downstream analysis tool. Most of them expect a matrix in PHYLIP format. The conversion can be done with a simple awk script but is tedious. It would be great if dashing could produce a phylip distance matrix for improved user experience.

See also https://github.com/marbl/Mash/issues/9.

**Comment by dnbaker** [comment]
Thank you for bringing it to my attention. I had assumed that an upper-triangular tabular format would be a reasonable starting-point, but this is a reasonable request. I'd certainly prefer native support over relying on accessory scripts.

Would the relaxed PHYLIP format be sufficient? I can imagine many cases where the 10 prefix characters per label are insufficient.

**Comment by kloetzl** [comment]
Don't bother with the 10 char limit; that is an ancient restriction.

**Comment by kloetzl** [comment]
Thank you for considering phylip distance matrix as an output format, however I have a few issues with your example.

 - Personally, I find the upper triangle format to be very confusing. Lower triangle is much more sensible as the alignment isn't messed up. At the same time I make my tools always output the [full square matrix](https://github.com/EvolBioInf/andi/blob/master/src/io.c#L309-L321) because that makes subsequent processing easier. Also it is only two times bigger.
 - Number such as 0.039389 are curious, because I doubt that dashing can accurately estimate the evolutionary distance up two six digits past the decimal dot.
 - The inclusion of `.fna.gz` in the sequence name is somewhat redundant.
 - The [code producing the triangle](https://github.com/dnbaker/dashing/blob/953f739f1a1c03979ac65db8f1bf7b1c05528da8/src/dashing.cpp#L331-L339) seems overly complicated.

**Comment by kloetzl** [comment]
I see that you have your reasons to keep the output as it is. Well, that means I have to write a wrapper to integrate dashing into my pipeline. But already the new output format helps. Feel free to close on merge.

> Thank you, the linked code is replaced with something clearer now.

Very much so!

**Comment by dnbaker** [comment]
I've merged this into master, but I'd still like to consider an option for full matrix PHYLIP output. I'd be tempted to do so by emitting as binary and then replacing that file with the desired human-readable form. This would add some processing time, but at least you wouldn't need to use your own script.
