### ISSUE TITLE
Error while cloning submodule

### ISSUE THREAD

**Issue by mihkelvaher** [dnbaker/dashing#84]
Hi!
There seems to be something wrong with the way submodules are cloned:
```
git clone --recursive https://github.com/dnbaker/dashing

Cloning into 'dashing'...
remote: Enumerating objects: 2879, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 2879 (delta 18), reused 40 (delta 12), pack-reused 2821
Receiving objects: 100% (2879/2879), 897.90 MiB | 40.66 MiB/s, done.
Resolving deltas: 100% (1466/1466), done.
Checking out files: 100% (57/57), done.
Submodule 'bonsai' (https://github.com/dnbaker/bonsai) registered for path 'bonsai'
Cloning into 'bonsai'...
remote: Enumerating objects: 7340, done.
remote: Counting objects: 100% (1437/1437), done.
remote: Compressing objects: 100% (1008/1008), done.
remote: Total 7340 (delta 440), reused 1356 (delta 412), pack-reused 5903
Receiving objects: 100% (7340/7340), 75.97 MiB | 25.51 MiB/s, done.
Resolving deltas: 100% (4792/4792), done.
fatal: reference is not a tree: f81114f11e811e69d552e9bbdcc2343582f629d4
Unable to checkout 'f81114f11e811e69d552e9bbdcc2343582f629d4' in submodule path 'bonsai'
```

**Comment by dnbaker** [comment]
Hi Mihkel,

Thanks for letting me know! I'll look into it and get it addressed today.

Best,

Daniel

**Comment by dnbaker** [comment]
Checking in on this --

To speed up download/installation, I've reduced the number of actual submodules. It seems I introduced a bug in the process, but it seems to be fixed now.

Would you try it again and let me know how it goes?

Thanks,

Daniel

**Comment by mihkelvaher** [comment]
Cloning and compiling run successfully
(just from some `src/sketch_and_cmp.h:199:25: warning: enumeration value ‘RK’ not handled in switch [-Wswitch]` warnings).
Calculating distances seems to work.

Thanks!

**Comment by dnbaker** [comment]
Awesome! And yes - that was an enum value that wasn't actually used. I've corrected this [here](https://github.com/dnbaker/dashing/pull/86), and you should be good to go. Thanks!
